name: release
on:
  push:

jobs:
  release:
    name: release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - run: make -j16 release

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/server.apkovl.tar.gz
            ipxe/ipxe/src/bin-x86_64-efi/ipxe.efi
            ipxe.cfg
            boot.cfg
